webapp/admin/views.py
from flask import Blueprint, render_template

from webapp.user.decorators import admin_required

blueprint = Blueprint('admin', __name__, url_prefix='/admin')

@blueprint.route('/')
@admin_required
def admin_index():
	title = 'Admin panel'
	return render_template('admin/index.html', page_title=title)

webapp/user/views.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import current_user, login_user, logout_user

from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User
from webapp.db  import db
from webapp.utils import get_redirect_target


blueprint = Blueprint('user', __name__, url_prefix='/users')

@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(get_redirect_target)
    title = 'Authorization'
    login_form = LoginForm()
    return render_template('user/login.html', page_title=title, form=login_form)

@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('Successfully logged in!')
            return redirect(url_for('news.index'))
    flash('Wrong credentials!')
    return (redirect(url_for('user.login')))

@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Logged out successfully')
    return redirect(get_redirect_target)

@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('news.index'))
    title = 'Registration'
    registration_form = RegistrationForm()
    return render_template('user/registration.html', page_title=title, form=registration_form)

@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        news_user = User(username=form.username.data, email=form.email.data, role='user')
        news_user.set_password(form.password.data)
        db.session.add(news_user)
        db.session.commit()
        flash('Registration successful')
        return redirect(url_for('user.login'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Error in field {}: {}'.format(getattr(form, field).label.text, error))
    return redirect(url_for('user.register'))

webapp/templates/base.html
<!-- <html>
        <head>
            <title>{{ page_title }}</title>
        </head>
        <body>
        	
        	<h1>
	        	{% if weather %}
	            	Weather is {{ weather.temp_C }}, feels like {{ weather.FeelsLikeC}}
	        	{% else %}
	        		Service is unavailable
	        	{% endif %}
        	</h1>
        </body>
    </html> -->

    <!doctype html>
    <html lang="en">
      <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/default.min.css">
        <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js"></script>
        <script>hljs.initHighlightingOnLoad();-</script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    
        <title>{{ page_title }}</title>
      </head>
      <body>
          {% include "menu.html" %}
        <div class="container">
            <h1>{{ page_title }}</h1>
            {% block content %}{% endblock %}
        </div>
    
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
      </body>
    </html>

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">LP News</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
  
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Main Page</a>
                </li>
            </ul>
            
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            <ul class="navbar-nav">
                <li class="nav-item">
                    {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <span class="nav-link">Hello, {{ current_user.username }}!</span>
                        </li>
                        {% if current_user.is_admin %}
                        <li class="nav-item">
                            <a class="nav-link" href=" {{ url_for('admin.admin_index') }} ">Admin</a>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href=" {{ url_for('user.logout') }} ">Log Out</a>
                        </li>
                    {% else %}
                        <a class="nav-link" href=" {{ url_for('user.login') }} ">Login</a>
                    {% endif %}

                </li>
            </ul>
        </div>
  </nav>

webapp/templates/messages.html
{% with messages = get_flashed_messages() %}
	{% if messages %}
	<div class="alert alert-warning" role="alert">
	    {% for message in messages %}
	        {{ message }}<br>
	    {% endfor %}
	</div>
	{% endif %}
{% endwith %}